repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-builtin-literals
        args: ['--no-allow-dict-kwargs']
    -   id: trailing-whitespace
        exclude: \.(md)
        exclude: ^secret/tls.*
        exclude: secret/*
    -   id: end-of-file-fixer
        exclude: secret/*
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    -   id: flake8
        args: []
        exclude: ^test_data/
        additional_dependencies: [pep8-naming]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8
-   repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.34.dss
    hooks:
    -   id: detect-secrets # pragma: whitelist secret
        args: [--baseline, .secrets.baseline, --use-all-plugins, --no-keyword-scan ]
