apiVersion: v1
kind: Service
metadata:
  name: gd-ingest
  labels:
    name: gd-ingest
    type: service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    name: gd-ingest
  type: ClusterIP
