apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gd-revoker
  labels:
    app: gd-revoker
    type: ingress
spec:
  rules:
  - host: gd-revoker.mycompany.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gd-revoker
            port:
              number: 80
  tls:
  - hosts:
    - gd-revoker.mycompany.com
    secretName: gd-tls-revoker-chained-cert
