---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  selector:
    matchLabels:
      app: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      volumes:
      - name: gd-secret
        secret:
          secretName: gd-secret-1.0.0
          items:
          - key: vault_prod_conf
            path: vault.conf
      - name: vault-init-script
        configMap:
          name: vault-init-script
      containers:
      - name: vault
        image: vault:1.4.3
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: gd-secret
          mountPath: "/gd-secret"
          readOnly: true
        - name: vault-init-script
          mountPath: /vault-init-script/
        ports:
        - containerPort: 8200
        env:
          - name: VAULT_DEV_ROOT_TOKEN_ID
            value: vault_root
          - name: GD_VAULT_CONF
            value: "/gd-secret/vault.conf"
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - /vault-init-script/vault_init.sh
      - name: vault-client
        image: vault:1.4.3
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 1
            memory: 1Gi
        env:
          - name: VAULT_ADDR
            value: 'http://127.0.0.1:8200'
          - name: VAULT_TOKEN
            value: vault_root
        command: ['/bin/sleep', '36000']
---
kind: Service
apiVersion: v1
metadata:
  name: vault
spec:
  selector:
    app: vault
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
